### ISSUE TITLE
Zero Blocks visual identity

### ISSUE THREAD

**Issue by kdinev** [Infragistics/zero-blocks#45]
Creating a visual identity for Zero Blocks:

1. Create logo
2. Define visual identity style (styleguide):
    A. imagery use (overlays, masking shapes, etc)
    B. fonts (used for websites and promo materials)
    C. colors (define base colors and color scheme)
    D. define iconography styles (round/edgy/mixed/lines/filled)

**Comment by kdinev** [comment]
@simeonoff Should this one be closed or there is more work to be done?

**Comment by simeonoff** [comment]
@kdinev can be closed.
